//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Discussions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discussions()
        {
            this.Comments = new HashSet<Comments>();
        }

        [Key]
        public int DiscussionID { get; set; }
        public int PublishID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual FilmPublishings FilmPublishings { get; set; }
        public virtual Users Users { get; set; }

        public int CommentCount { get; set; }
        public int CurrentUserComCount { get; set; }
    }
}
