//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesActors
    {
        public int MoviesActorsID { get; set; }
        public int MoviesID { get; set; }
        public int ActorsID { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
