//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studio
    {
        public int StudioID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual Countries Countries { get; set; }
    }
}
