//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceWork.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CommentID { get; set; }
        public int DiscussionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Contenting { get; set; }
    
        public virtual Discussions Discussions { get; set; }
        public virtual Users Users { get; set; }
    }
}
