//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceWork.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmPublishings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilmPublishings()
        {
            this.Discussions = new HashSet<Discussions>();
        }
    
        public int PublishID { get; set; }
        public int MovieID { get; set; }
        public string Status { get; set; }
        public System.DateTime PublishDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discussions> Discussions { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
