//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceWork.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesDirectors
    {
        public int MoviesDirectorsID { get; set; }
        public int MoviesID { get; set; }
        public int DirectorsID { get; set; }
    
        public virtual Directors Directors { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
