//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceWork.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesCountries
    {
        public int MovieCountryID { get; set; }
        public int MovieID { get; set; }
        public int CountryID { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
